@startuml

abstract Product {
  + use()
}

class ConcreteProduct {
  + use()
}

Product <|.. ConcreteProduct

abstract Factory {
  + Product factoryMethod()
}

class ConcreteFactory {
  + Product factoryMethod()
}
note right: return new ConcreteProduct():

Factory <|.. ConcreteFactory

ConcreteProduct <.. ConcreteFactory

@enduml
